NumPy - Helps in building multidimensional arrays and is used for faster operations. Main Advantages: vectorized operations, Fast and less memory.

In [4]:
import numpy as np

Arrays

In [11]:
a1 = np.array([1,2,3]) #1d array
a2 = np.array([[1,2],[3,4]]) #2d array

In [18]:
# array and it's dimensions
print(f"array: {a1}, dimension: {np.shape(a1)}")
print(f"array: {a2}, dimension: {np.shape(a2)}")

array: [1 2 3], dimension: (3,)
array: [[1 2]
 [3 4]], dimension: (2, 2)


Some common utils:

In [30]:
arr = np.arange(10)
arr_zeros = np.zeros((3,2))
arr_ones = np.ones((3,2))
arr_spacing = np.linspace(0,10,5) #used for plotting, divides the interval such that there are n numbers (a,b,n)

In [31]:
print(arr)
print(arr_zeros)
print(arr_ones)
print(arr_spacing)

[0 1 2 3 4 5 6 7 8 9]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[ 0.   2.5  5.   7.5 10. ]


Array Slicing:

In [32]:
arr = np.arange(10,60,10)

In [34]:
print(arr[1:4])

[20 30 40]


In [35]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [36]:
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
print(arr_2d[0]) #prints single row

[1 2 3]


In [39]:
print(arr_2d[1,2]) #prints particular element

6


In [43]:
print(arr_2d[:,2]) #prints single column

[3 6 9]


In [47]:
print(arr_2d[1:3,1:3]) #printing submatrix

[[5 6]
 [8 9]]


Reshaping:


In [50]:
arr = np.arange(10)
reshaped = arr.reshape(2,5) # rule is: Total elements must remain same.

In [51]:
print(arr)
print(reshaped)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [56]:
auto_shape_1 = arr.reshape(-1, 5) #commonly used, auto calculates rows
auto_shape_2 = arr.reshape(5, -1) #autocalculates columns
print(auto_shape_1)
print(auto_shape_2)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


Broad-Casting:

In [58]:
a1 = np.arange(3)
print(a1+10) #scalar broadcast, adds value to each element

[10 11 12]


In [62]:
a2 = np.array([[1,2],[3,4]])
a3 = np.array([[10,20]])
print(a2+a3) #vector broadcast, adds vector to the matrix

[[11 22]
 [13 24]]


Broadcasting Rules:

Compare shapes from right to left. Compatible if:

equal OR
one dimension is 1

In [63]:
(2,3)
(1,3)
#works since one dimension is 1

(1, 3)

In [64]:
(2,3)
(3,)
#works since the right to left dimensions match

(3,)

In [66]:
(2,3)
(2,2)
#invalid broadcasting, as the dimensions isn't matching.

(2, 2)